FROM ubuntu:20.04
WORKDIR /.termplugin
RUN apt-get update && apt-get install -y python3-pip
COPY requirements.txt .
RUN yes | pip install -r requirements.txt
COPY . .
EXPOSE 5000
WORKDIR /
CMD ["python3", "/.termplugin/app.py"]